# Generated by Django 5.0.6 on 2024-05-23 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
        migrations.RenameField(
            model_name="fooditem",
            old_name="category_name",
            new_name="category",
        ),
    ]
