# Generated by Django 5.0.6 on 2024-06-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_order_feedbacks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="is_ordered",
            field=models.BooleanField(default=True),
        ),
    ]
